solution-code/config/routes.rb
Rails.application.routes.draw do

  root to: "welcome#index"

  get "/login", to: "sessions#new"

  post "/sessions", to: "sessions#create"

  delete "/sessions", to: "sessions#destroy"

  get "/sign_up", to: "users#new", as: "sign_up"

  resources :users, only: [:new, :create, :show, :index]

  # handles all unknown requests and sends them home
  get "*path" => "welcome#index"

end

solution-code/app/models/user.rb
class User < ActiveRecord::Base

  # refactor below
  has_secure_password

  # ensure emails are unique
  validates :email, presence:true, uniqueness: true 

  # BCrypt::Engine.cost = 12

  # # email & password_digest fields must exist
  # validates :email, :password_digest, presence: true
  # # a user must have a password & password confirmation field
  # # the fields are match against each other but never persisted to the database
  # validates_confirmation_of :password
  # # TODO: add validator for unique emails

  # # to authenticate the user using bcrypt's built in 
  # def authenticate(unencrypted_password)
  #   secure_password = BCrypt::Password.new(self.password_digest)
  #   # check that a hashed version of the unencrypted password is the same as the secure password
  #   # the method `==` has been modified for `secure_password` to first hash whatever it's comparing to
  #   if secure_password == unencrypted_password
  #     # return the user
  #     self
  #   else
  #     false
  #   end
  # end

  # def password=(unencrypted_password)
  #   #raise scope of password to instance
  #   @password = unencrypted_password
  #   self.password_digest = BCrypt::Password.create(@password)
  # end

  # def password
  #   #get password, equivalent to `attr_reader :password`
  #   @password
  # end

  # has_secure_password does not give us `::confirm`

  def self.confirm(email_param, password_param)
    user = User.find_by_email(email_param)
    user.authenticate(password_param)
  end

end

solution-code/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
 

  def current_user
    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  end

  def require_login
    if !current_user
      redirect_to root_path #halt's request cycle
    end
  end

  helper_method :current_user #make it available in views
end

solution-code/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to current_user if current_user 
  end

  def create
    #pass in array that user_params returns as arguments using a splat
    user = User.confirm(params[:email], params[:password])
    if user
      #this creates the session, logging in the user
      session[:user_id] = user.id
      #redirect to the show page
      redirect_to user_path(user.id)
    else
      #there was an error logging the user in
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

solution-code/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: :index

  # to illustrate a before_action
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #login user
      session[:user_id] = @user.id
      #redirect to user#show w/ success message
      redirect_to @user, flash: { success: "Successfully signed up!" }
    else
      #there was an error, go back to signup page & display message
      redirect_to sign_up_path, flash: { error: @user.errors.full_messages.to_sentence }
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

solution-code/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

solution-code/app/helpers/application_helper.rb
module ApplicationHelper
  # def flash_messages(opts = {})
  #   flash.each do |msg_type, message|
  #     concat content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
  #             concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
  #             concat message 
  #           end
  #   end
  #   nil
  # end
  
  # # this method assumes you are using bootstrap in your project
  # def bootstrap_class_for flash_type
  #   { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  # end
end

solution-code/app/helpers/sessions_helper.rb
module SessionsHelper
end

solution-code/app/helpers/users_helper.rb
module UsersHelper
end

solution-code/app/helpers/welcome_helper.rb
module WelcomeHelper
end

solution-code/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "partials/nav" %>

<%= bootstrap_flash %>

<%= yield %>

</body>
</html>

solution-code/app/views/partials/_nav.html.erb
<%= link_to "Home", root_path %>

<% if current_user %>

<%= link_to "Profile", user_path(current_user) %>

<%= link_to "Logout", sessions_path, method: :delete %> 
<% else %>

<%= link_to "Signup", sign_up_path %>

<span>or</span>

<%= link_to "Login", login_path %>

<% end %>

solution-code/app/views/users/index.html.erb
<h1>All the users!</h1>

<p>This page is only accessible if you are logged in</p>

<ul>
<% @users.each do |user| %>
	<li><%= user.email %></li>
<% end %>
</ul>

solution-code/app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_for @user do |f| %>
	<span>Email: </span><br>
	<%= f.text_field :email, required: true %><br>

	<span>Password: </span><br>
	<%= f.password_field :password, required: true %><br>

	<span>Password confirmation: </span><br>
	<%= f.password_field :password_confirmation, required: true %><br>

	<%= f.submit "Signup" %>
<% end %>

solution-code/app/views/users/show.html.erb
<h1>Hello <%= @user.email %></h1>

solution-code/app/views/welcome/index.html.erb
<h1>You're Home</h1>